### ISSUE TITLE
PERMISSION_DENIED: User not authorized to perform this action

### ISSUE THREAD

**Issue by praveenuchiha** [logstash-plugins/logstash-output-google_pubsub#14]
Hi, I am trying to use this plugin to publish to pub/sub from outside the google Env. I have created a service account with the Pub/Sub Publisher role and reference the Json file in the config. But i get a permission denied when i restart logstash (Can confirm 403 code from GCP API console for that service account). I tried giving the service account Pub/Sub Admin role and had no luck(tried project owner just to test it and no luck).
 I can also confirm LS picking up the key on initialization 
` Initializing Google API client on projects/my-project/topics/logstash-input key: /etc/logstash/gcp-cloud-423478239.json`
Here is the error i get:
` :error=>"io.grpc.StatusRuntimeException: PERMISSION_DENIED: User not authorized to perform this action."} `
Not sure what i am missing here. Any help would be appreciated.
Here is my LS config:
```output {
  google_pubsub {
        project_id => "my-project"
        topic => "logstash-input"
        json_key_file => "/etc/logstash/gcp-cloud-423478239.json"
  } 
}

**Comment by loripino21** [comment]
I have the same problem. How did you solve the issue? Thanks

**Comment by jdieguezbean** [comment]
Same, any update on this thread?
